class Meal:
    def __init__(self, mealID: str, name: str, mealType: str, dayOfWeek: str, assignedCook: str, familyGroupID: str):
        self.mealID = mealID
        self.name = name
        self.mealType = mealType
        self.dayOfWeek = dayOfWeek
        self.assignedCook = assignedCook
        self.familyGroupID = familyGroupID

    
    #ADDS MEAL
    def addMeal(self):
        if self.name == "":
            print("Meal name cannot be blank")
        return
    
    #DELETES MEAL
    def deleteMeal(self):
        self.name = ""
        self.mealType = ""
        self.dayOfWeek = ""

    #EDITS MEAL    
    def editMeal(self, newName: str, newCook: str):
        if newName == "":
            print("Meal name cannot be blank")
            return
        self.name = newName
        self.assignedCook = newCook

    #SORTS BY DAY
    def sortByDay(self):
        sortedMeals = sorted(meals, key=lambda ("dayOfWeek"))
        return sortedMeals
    

class User:
    def __init__(self, name: str, email: str, password: str):
        self.userID = "firebase generates ID"
        self.name = name
        self.email = email
        self.password = password
        self.familyGroupID = ""

    #CHECK IF EMAIL AND PASSWORD IS BLANK
    def register(self):
        if self.email or self.password == "":
            print("Email and Password cannot be blank")
            return
        return self
    
    #CHECK IF EMAIL AND PASSWORD ARE NOT BLANK 
    def login(self):
        if self.email or self.password == "":
            print("Email and Password cannot be blank")
            return
        return self
    
    #LOGS OUT
    def logout(self):
        self.familyGroupID = ""


class FamilyGroup:
    def __init__(self, createdBy: str, memberIDs: list):
        self.groupID = "Firebase generates ID"
        self.groupCode = "Firebase generates code"
        self.memberIDs = memberIDs
        self.createdBy = createdBy

    #CREATES GROUP
    def createGroup(self):
        return self.groupCode
    
    #JOIN GROUP
    def joinGroup(self, userID: str, enteredCode: str):
        if enteredCode != self.groupCode:
            print("Incorrect group code")
            return 
        else:
            self.memberIDs.append(userID)

        #GET MEMBERS
        def getMembers(self):
            return  self.memberIDs
        
 GroceryItems = []
class GroceryItem:
    def __init__(self, name: str, addedBy: str, familyGroupID: str, isPurchased: bool):
        self.itemID = "generated by firebase"
        self.name = name
        self.addedBy = addedBy
        self.familyGroupID = familyGroupID
        self.isPurchased = False

    #ADDS ITEM
    def addItem(self):
        if self.name == "":
            return "Item name cannot be blank"
        else:
            return self
        
    #UPDATES NAME
    def updateName(self, newName):
        if newName == "":
            return "Item name cannot be blank"
        else:
            self.name = newName
        
    
    #DELETES ITEM
    def deleteItem(self):
        self.name = ""
        self.isPurchased = False
        self.addedBy = ""

    #MARKS AS PURCHASED
    def markAsPurchased(self):
        self.isPurchased = not self.isPurchased

    #SORTS WETHER ITEM IS PURCHASED
    def sortByPurchased(self):
        stillNeeded = []
        alreadybought = []
        for i in GroceryItems:
            if i == False:
                stillNeeded.append(i)
            else:
                alreadybought.append(i)
        return stillNeeded + alreadybought